services:
  dev:
    build:
      context: .
    command: sleep infinity
    volumes:
      - ..:/workspace
    depends_on:
      - cosmosdb
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    hostname: cosmosdb.domain
    ports:
      - 8081