name: Pre-build devcontainer image
on: 
  push:
    branches:
      - main
jobs:
  validate:
    name: Validate using .NET test project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3
      - name: Build devcontainer image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/azure-samples/cosmos-db-nosql-query-samples-devcontainer
          cacheFrom: ghcr.io/azure-samples/cosmos-db-nosql-query-samples-devcontainer
          push: always