name: Pre-build devcontainer image
on: 
  push:
    branches:
      - main
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build devcontainer image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/azure-samples/cosmos-db-nosql-query-samples-devcontainer
          cacheFrom: ghcr.io/azure-samples/cosmos-db-nosql-query-samples-devcontainer
          push: always
