name: Validate query samples
on:
  workflow_dispatch:
  pull_request:
jobs:
  validate:
    name: Validate query samples
    runs-on: ubuntu-latest
    services:
      cosmosdb:
        image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
        options: >-
          --health-cmd "curl --insecure https://localhost:8081/_explorer/emulator.pem"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 8081:8081
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Install SSL certificate
        run: |
          curl --insecure https://127.0.0.1:8081/_explorer/emulator.pem > ~/emulatorcert.crt
          sudo cp ~/emulatorcert.crt /usr/local/share/ca-certificates/
          sudo rm -f /usr/local/share/ca-certificates/certificate.crt
          sudo update-ca-certificates --fresh
      - name: Run .NET test
        run: dotnet test --logger "console" --logger "trx;verbosity=detailed"
        env:
          COSMOSDB__CONNECTIONSTRING: "AccountEndpoint=https://127.0.0.1:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=="
        working-directory: ./validate/test
      - name: Upload TRX test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: validate/test/TestResults/**/*.trx
          