name: Validate query samples
on:
  workflow_dispatch:
  pull_request:
jobs:
  validate:
    name: Validate query samples
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:8.0
    services:
      cosmosdb:
        image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
        options: >-
          --hostname "cosmosdb.domain"
          --network "host"
        ports:
          - 8081:8081
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install SSL certificate
        run: |
          curl --insecure https://cosmosdb.domain:8081/_explorer/emulator.pem > ~/emulatorcert.crt
          sudo cp ~/emulatorcert.crt /usr/local/share/ca-certificates/
          sudo update-ca-certificates
      - name: Run .NET test
        run: dotnet test --logger "console" --logger "trx;verbosity=detailed"
        env:
          COSMOSDB__CONNECTIONSTRING: "AccountEndpoint=https://cosmosdb.domain:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=="
        working-directory: ./validate/test
      - name: Upload TRX test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: validate/test/TestResults/**/*.trx
          