name: Validate NoSQL query samples
on: pull_request
jobs:
  validate:
    name: Validate using .NET test project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
