name: Validate NoSQL query samples
on: pull_request
jobs:
  validate:
    name: Validate using .NET test project
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:8.0
    services:
      cosmosdb:
        image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
        ports:
          - 8081:8081
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
      - name: Run .NET test
        run: dotnet test --logger "console" --logger "trx;verbosity=detailed"
        working-directory: ./validate/test
      - name: Upload TRX test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./validate/test/TestResults/**/*.trx
